import { randomUUID } from 'node:crypto';
import { afterAll, beforeEach, describe, expect, it } from 'vitest';
import { prisma, disconnectPrisma } from '../src/lib/prisma.js';
import { createSession } from '../src/store/auth.js';
import { hashMember } from '../src/store/identity.js';
import { buildServer } from '../src/http/server.js';
async function setup() { const owner = await prisma.user.create({ data: { email: `${randomUUID()}@teste.local` } }); const session = await createSession(owner.id); const community = await prisma.community.create({ data: { platform: 'youtube', externalId: `UC_${randomUUID()}`, name: 'Canal Notif', ownerId: owner.id } }); const memberHash = hashMember('youtube', 'autor-notif'); await prisma.memberIdentity.create({ data: { memberHash, platform: 'youtube', externalUserId: 'autor-notif', username: 'Ciclana', isBot: false } }); const transition = await prisma.levelTransition.create({ data: { memberHash, communityId: community.id, fromLevel: 1, toLevel: 2, scoreAt: 10, reason: 'promotion' } }); return { session, community, transition }; }
beforeEach(async () => { await prisma.levelTransition.deleteMany(); await prisma.memberIdentity.deleteMany(); await prisma.memberEvent.deleteMany(); await prisma.community.deleteMany(); await prisma.job.deleteMany(); await prisma.session.deleteMany(); await prisma.user.deleteMany(); }); afterAll(async () => { await disconnectPrisma(); });
describe('notificações, busca e config', () => {
  it('lista e marca notificações', async () => { const { session, transition } = await setup(); const app = buildServer(); const list = await app.inject({ method: 'GET', url: '/notificacoes', cookies: { engagemend_session: session.id } }); expect(list.json()[0].id).toBe(transition.id.toString()); expect(list.json()[0].lida).toBe(false); expect((await app.inject({ method: 'POST', url: `/notificacoes/${transition.id}/lida`, cookies: { engagemend_session: session.id } })).statusCode).toBe(200); expect((await prisma.levelTransition.findUnique({ where: { id: transition.id } }))?.readAt).not.toBeNull(); expect((await app.inject({ method: 'POST', url: '/notificacoes/lidas', cookies: { engagemend_session: session.id } })).json().lidas).toBe(0); });
  it('busca comunidade e devolve configuração', async () => { const { session, community } = await setup(); const app = buildServer(); expect((await app.inject({ method: 'GET', url: '/busca?q=Notif', cookies: { engagemend_session: session.id } })).json().comunidades[0].id).toBe(community.id); const config = await app.inject({ method: 'GET', url: '/configuracoes', cookies: { engagemend_session: session.id } }); expect(config.statusCode).toBe(200); expect(config.json().pesos).toBeDefined(); });
});
