import { randomUUID } from 'node:crypto';
import { afterAll, beforeEach, describe, expect, it, vi } from 'vitest';
import { prisma, disconnectPrisma } from '../src/lib/prisma.js';
import { createSession } from '../src/store/auth.js';
vi.mock('../src/http/youtube-channel-info.js', () => ({ fetchYoutubeChannelInfo: vi.fn(async (id: string) => ({ name: `Canal ${id}` })) }));
const { fetchYoutubeChannelInfo } = await import('../src/http/youtube-channel-info.js'); const { buildServer } = await import('../src/http/server.js');
async function auth() { const user = await prisma.user.create({ data: { email: `${randomUUID()}@teste.local` } }); return { cookie: (await createSession(user.id)).id, userId: user.id }; }
beforeEach(async () => { await prisma.memberEvent.deleteMany(); await prisma.community.deleteMany(); await prisma.job.deleteMany(); await prisma.session.deleteMany(); await prisma.magicLinkToken.deleteMany(); await prisma.user.deleteMany(); vi.mocked(fetchYoutubeChannelInfo).mockClear(); }); afterAll(async () => { await disconnectPrisma(); });
describe('POST /conexoes', () => {
  it('cria comunidade sincronizando e job', async () => { const { cookie } = await auth(); const response = await buildServer().inject({ method: 'POST', url: '/conexoes', cookies: { engagemend_session: cookie }, payload: { plataforma: 'youtube', identificador: 'UC_ABC123' } }); expect(response.statusCode).toBe(201); expect(response.json().estadoSync).toBe('sincronizando'); expect((await prisma.job.findUnique({ where: { id: response.json().jobId } }))?.kind).toBe('youtube_sync'); });
  it('duplicado devolve 409', async () => { const first = await auth(); await buildServer().inject({ method: 'POST', url: '/conexoes', cookies: { engagemend_session: first.cookie }, payload: { plataforma: 'youtube', identificador: 'UC_DUP' } }); const second = await auth(); expect((await buildServer().inject({ method: 'POST', url: '/conexoes', cookies: { engagemend_session: second.cookie }, payload: { plataforma: 'youtube', identificador: 'UC_DUP' } })).statusCode).toBe(409); });
  it('sem sessão devolve 401', async () => { expect((await buildServer().inject({ method: 'POST', url: '/conexoes', payload: { plataforma: 'youtube', identificador: 'UC_X' } })).statusCode).toBe(401); });
});
describe('jobs', () => { it('job do próprio dono é visível e de outro dono não', async () => { const owner = await auth(); const created = await buildServer().inject({ method: 'POST', url: '/conexoes', cookies: { engagemend_session: owner.cookie }, payload: { plataforma: 'youtube', identificador: 'UC_JOB' } }); const jobId = created.json().jobId; expect((await buildServer().inject({ method: 'GET', url: `/api/jobs/${jobId}`, cookies: { engagemend_session: owner.cookie } })).statusCode).toBe(200); const stranger = await auth(); expect((await buildServer().inject({ method: 'GET', url: `/api/jobs/${jobId}`, cookies: { engagemend_session: stranger.cookie } })).statusCode).toBe(404); }); });
