import { randomUUID } from 'node:crypto';
import { afterAll, beforeEach, describe, expect, it } from 'vitest';
import { prisma, disconnectPrisma } from '../src/lib/prisma.js';
import { createSession } from '../src/store/auth.js';
import { hashMember } from '../src/store/identity.js';
import { buildServer } from '../src/http/server.js';
async function setup() { const owner = await prisma.user.create({ data: { email: `${randomUUID()}@teste.local` } }); const session = await createSession(owner.id); const community = await prisma.community.create({ data: { platform: 'youtube', externalId: `UC_${randomUUID()}`, name: 'Canal Teste', ownerId: owner.id } }); const memberHash = hashMember('youtube', 'autor1'); await prisma.memberIdentity.create({ data: { memberHash, platform: 'youtube', externalUserId: 'autor1', username: 'Fulano', isBot: false } }); await prisma.memberEvent.create({ data: { memberHash, guildId: community.externalId, communityId: community.id, source: 'youtube', eventType: 'comment_sent', refId: 'ev1', occurredAt: new Date() } }); await prisma.memberProfile.create({ data: { memberHash, currentLevel: 2, score30d: 12.5, scoreLifetime: 12.5, levelSince: new Date(), firstActivityAt: new Date(), lastActivityAt: new Date(), computedAt: new Date(), weightsVersion: 'v0.1.0-uncalibrated' } }); return { session, community, memberHash }; }
beforeEach(async () => { await prisma.levelTransition.deleteMany(); await prisma.memberProfile.deleteMany(); await prisma.memberEvent.deleteMany(); await prisma.memberIdentity.deleteMany(); await prisma.community.deleteMany(); await prisma.job.deleteMany(); await prisma.session.deleteMany(); await prisma.user.deleteMany(); }); afterAll(async () => { await disconnectPrisma(); });
describe('comunidades', () => {
  it('lista somente do dono', async () => { const { session, community } = await setup(); const response = await buildServer().inject({ method: 'GET', url: '/comunidades', cookies: { engagemend_session: session.id } }); expect(response.statusCode).toBe(200); expect(response.json()[0].id).toBe(community.id); });
  it('detalhe, ownership e inexistente', async () => { const { session, community } = await setup(); const app = buildServer(); expect((await app.inject({ method: 'GET', url: `/comunidades/${community.id}`, cookies: { engagemend_session: session.id } })).json().nome).toBe('Canal Teste'); const stranger = await prisma.user.create({ data: { email: `${randomUUID()}@teste.local` } }); const strangerSession = await createSession(stranger.id); expect((await app.inject({ method: 'GET', url: `/comunidades/${community.id}`, cookies: { engagemend_session: strangerSession.id } })).statusCode).toBe(404); expect((await app.inject({ method: 'GET', url: '/comunidades/nope', cookies: { engagemend_session: session.id } })).statusCode).toBe(404); });
  it('ranking, eventos, membro, resumo e relatório', async () => { const { session, community, memberHash } = await setup(); const app = buildServer(); const ranking = await app.inject({ method: 'GET', url: `/comunidades/${community.id}/ranking`, cookies: { engagemend_session: session.id } }); expect(ranking.json().itens[0].pontuacao).toBe(12.5); const events = await app.inject({ method: 'GET', url: `/comunidades/${community.id}/eventos`, cookies: { engagemend_session: session.id } }); expect(events.json().itens).toHaveLength(1); expect(events.json().membros[memberHash].nome).toBe('Fulano'); const member = await app.inject({ method: 'GET', url: `/comunidades/${community.id}/membros/${memberHash}`, cookies: { engagemend_session: session.id } }); expect(member.json().membro.pontuacao).toBe(12.5); expect((await app.inject({ method: 'GET', url: `/comunidades/${community.id}/resumo`, cookies: { engagemend_session: session.id } })).json().totalMembros).toBe(1); expect((await app.inject({ method: 'GET', url: `/comunidades/${community.id}/relatorio?dias=30`, cookies: { engagemend_session: session.id } })).json().distribuicao['2']).toBe(1); });
});
