import type { FastifyInstance } from 'fastify';
import { prisma } from '../lib/prisma.js';
import { enqueueJob } from '../store/jobs.js';
type Owned = { id: string; platform: string; externalId: string; name: string; syncState: string; syncedAt: Date };
async function owned(id: string, ownerId: string): Promise<Owned | null> { return prisma.community.findFirst({ where: { id, ownerId }, select: { id: true, platform: true, externalId: true, name: true, syncState: true, syncedAt: true } }); }
function initials(name: string) { return name.split(/\s+/).filter(Boolean).slice(0, 2).map((p) => p[0]!.toUpperCase()).join(''); }
async function memberCount(id: string) { return (await prisma.memberEvent.findMany({ where: { communityId: id }, distinct: ['memberHash'], select: { memberHash: true } })).length; }
function dto(c: Owned, membros: number) { return { id: c.id, plataforma: c.platform, nome: c.name, iniciais: initials(c.name), membros, online: 0, estadoSync: c.syncState, sincronizadaEm: c.syncedAt.toISOString() }; }
async function need(id: string, ownerId: string, reply: { code: (n: number) => { send: (v: unknown) => unknown } }) { const c = await owned(id, ownerId); if (!c) { reply.code(404).send({ error: 'comunidade não encontrada' }); return null; } return c; }
export async function registerComunidadesRoutes(app: FastifyInstance): Promise<void> {
  app.get('/comunidades', async (request) => { const rows = await prisma.community.findMany({ where: { ownerId: request.user.id, disabledAt: null }, select: { id: true, platform: true, externalId: true, name: true, syncState: true, syncedAt: true } }); return Promise.all(rows.map(async (c) => dto(c, await memberCount(c.id)))); });
  app.get('/comunidades/:id', async (request, reply) => { const c = await need((request.params as { id: string }).id, request.user.id, reply); return c ? dto(c, await memberCount(c.id)) : undefined; });
  app.get('/comunidades/:id/ranking', async (request, reply) => { const id = (request.params as { id: string }).id; const c = await need(id, request.user.id, reply); if (!c) return; const hashes = (await prisma.memberEvent.findMany({ where: { communityId: id }, distinct: ['memberHash'], select: { memberHash: true } })).map((r) => r.memberHash); const [profiles, identities] = await Promise.all([prisma.memberProfile.findMany({ where: { memberHash: { in: hashes } }, orderBy: { score30d: 'desc' } }), prisma.memberIdentity.findMany({ where: { memberHash: { in: hashes } } })]); const byHash = new Map(identities.map((i) => [i.memberHash, i])); return { itens: profiles.map((p, n) => { const i = byHash.get(p.memberHash); const nome = i?.displayName ?? i?.username ?? p.memberHash.slice(0, 8); return { posicao: n + 1, membro: { id: p.memberHash, comunidadeId: id, plataforma: c.platform, nome, arroba: i?.username ?? '', iniciais: initials(nome), entrouEm: (i?.firstSeenAt ?? p.computedAt).toISOString() }, pontuacao: p.score30d, nivel: p.currentLevel, totalEventos: 0, ultimaAtividade: p.lastActivityAt?.toISOString() ?? null, tendencia: 'estavel', deltaPontuacao: 0, nivelAnterior: null }; }), proximoCursor: null }; });
  app.get('/comunidades/:id/eventos', async (request, reply) => { const id = (request.params as { id: string }).id; const c = await need(id, request.user.id, reply); if (!c) return; const events = await prisma.memberEvent.findMany({ where: { communityId: id }, orderBy: { occurredAt: 'desc' }, take: 50 }); const ids = await prisma.memberIdentity.findMany({ where: { memberHash: { in: [...new Set(events.map((e) => e.memberHash))] } } }); return { itens: events.map((e) => ({ id: e.id.toString(), plataforma: c.platform, comunidadeId: id, membroId: e.memberHash, tipo: e.eventType, ocorridoEm: e.occurredAt.toISOString(), payload: e.metadata })), proximoCursor: null, membros: Object.fromEntries(ids.map((i) => [i.memberHash, { nome: i.displayName ?? i.username, arroba: i.username, iniciais: initials(i.displayName ?? i.username) }])) }; });
  app.get('/comunidades/:id/membros/:membroId', async (request, reply) => { const { id, membroId } = request.params as { id: string; membroId: string }; const c = await need(id, request.user.id, reply); if (!c) return; const [p, i] = await Promise.all([prisma.memberProfile.findUnique({ where: { memberHash: membroId } }), prisma.memberIdentity.findUnique({ where: { memberHash: membroId } })]); if (!p || !i) return reply.code(404).send({ error: 'membro não encontrado' }); const nome = i.displayName ?? i.username; return { comunidade: dto(c, await memberCount(id)), membro: { membro: { id: membroId, comunidadeId: id, plataforma: c.platform, nome, arroba: i.username, iniciais: initials(nome), entrouEm: i.firstSeenAt.toISOString() }, pontuacao: p.score30d, nivel: p.currentLevel, totalEventos: 0, ultimaAtividade: p.lastActivityAt?.toISOString() ?? null, tendencia: 'estavel', deltaPontuacao: 0, nivelAnterior: null }, composicao: { consumo: p.axisConsumption, producao: p.axisProduction, reciprocidade: p.axisReciprocity, influencia: p.axisInfluence }, serie: [] }; });
  app.get('/comunidades/:id/resumo', async (request, reply) => { const id = (request.params as { id: string }).id; if (!await need(id, request.user.id, reply)) return; return { totalMembros: await memberCount(id) }; });
  app.get('/comunidades/:id/relatorio', async (request, reply) => { const id = (request.params as { id: string }).id; if (!await need(id, request.user.id, reply)) return; const hashes = (await prisma.memberEvent.findMany({ where: { communityId: id }, distinct: ['memberHash'], select: { memberHash: true } })).map((r) => r.memberHash); const profiles = await prisma.memberProfile.findMany({ where: { memberHash: { in: hashes } } }); const distribuicao: Record<string, number> = { '1': 0, '2': 0, '3': 0, '4': 0, '5': 0 }; for (const p of profiles) distribuicao[String(p.currentLevel)] = (distribuicao[String(p.currentLevel)] ?? 0) + 1; return { serie: [], composicao: {}, distribuicao }; });
  app.delete('/comunidades/:id', async (request, reply) => { const id = (request.params as { id: string }).id; if (!await need(id, request.user.id, reply)) return; await prisma.community.update({ where: { id }, data: { disabledAt: new Date() } }); return { id }; });
  for (const path of ['reconectar', 'sincronizar'] as const) app.post(`/comunidades/:id/${path}`, async (request, reply) => { const id = (request.params as { id: string }).id; const c = await need(id, request.user.id, reply); if (!c) return; if (c.platform === 'whatsapp') return reply.code(400).send({ error: 'WhatsApp não tem API pra ressincronizar — envie um novo export em POST /conexoes/whatsapp' }); await prisma.community.update({ where: { id }, data: { disabledAt: null, syncState: 'sincronizando' } }); const payload = c.platform === 'youtube' ? { channelId: c.externalId, channelName: c.name } : { guildId: c.externalId }; await enqueueJob(request.user.id, c.platform === 'youtube' ? 'youtube_sync' : 'discord_backfill', payload); return dto({ ...c, syncState: 'sincronizando' }, await memberCount(id)); });
}
